# Generated by Django 5.2.17 on 2026-09-16 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_count', models.PositiveIntegerField()),
                ('issued_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Serials generated'), ('EXPORTED', 'Label export downloaded'), ('RECONCILED', 'Quantities reconciled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('export_object_key', models.CharField(blank=True, max_length=500)),
                ('export_deleted_at', models.DateTimeField(blank=True, help_text='Export must be deleted within 24 hours of reconciliation.', null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_printed', models.PositiveIntegerField(default=0)),
                ('reconciled_rejected', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='catalog.batch')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='organizations.organization')),
            ],
            options={
                'db_table': 'print_job',
            },
        ),
        migrations.CreateModel(
            name='PackageUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_reference', models.CharField(max_length=64)),
                ('token_sha256', models.BinaryField(max_length=32)),
                ('lifecycle', models.CharField(choices=[('CREATED', 'Created'), ('PRINTED', 'Printed'), ('QC_PASSED', 'QC passed'), ('COVERED', 'Coated'), ('ACTIVE', 'Active'), ('REDEEMED', 'Redeemed'), ('VOID', 'Void')], default='CREATED', max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='catalog.batch')),
                ('print_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='serialization.printjob')),
            ],
            options={
                'db_table': 'package_unit',
            },
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['manufacturer', 'status'], name='print_job_manufac_43ac38_idx'),
        ),
        migrations.AddIndex(
            model_name='packageunit',
            index=models.Index(fields=['batch', 'lifecycle'], name='package_uni_batch_i_5a12f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='packageunit',
            constraint=models.UniqueConstraint(fields=('token_sha256',), name='uniq_unit_token_sha256'),
        ),
        migrations.AddConstraint(
            model_name='packageunit',
            constraint=models.UniqueConstraint(fields=('batch', 'external_reference'), name='uniq_unit_external_reference'),
        ),
    ]
