# Generated by Django 5.2.17 on 2026-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='export_ciphertext',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='export_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
