# Generated by Django 5.2.17 on 2026-09-16 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.CharField(max_length=80, unique=True)),
                ('algorithm', models.CharField(default='ML-DSA-65', max_length=20)),
                ('purpose', models.CharField(choices=[('ACTIVATION', 'Manufacturer activation credentials'), ('STATUS', 'Platform status and receipt envelopes'), ('ROOT', 'Offline root, authorises the manifest')], max_length=20)),
                ('public_key', models.BinaryField(max_length=4096)),
                ('private_key_reference', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired, still valid for historical credentials'), ('REVOKED', 'Revoked, triggers a verification hold')], default='ACTIVE', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signing_keys', to='organizations.organization')),
            ],
            options={
                'db_table': 'signing_key',
            },
        ),
        migrations.CreateModel(
            name='TrustManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('canonical_bytes', models.BinaryField()),
                ('signature', models.BinaryField(max_length=4096)),
                ('issued_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifests', to='trust.signingkey')),
            ],
            options={
                'db_table': 'trust_manifest',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='signingkey',
            index=models.Index(fields=['organization', 'purpose', 'state'], name='signing_key_organiz_bf5a23_idx'),
        ),
    ]
