# Generated by Django 5.2.17 on 2026-09-16 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_sha256', models.BinaryField(max_length=32)),
                ('installation_id', models.CharField(blank=True, max_length=64)),
                ('app_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consumer_session',
                'constraints': [models.UniqueConstraint(fields=('credential_sha256',), name='uniq_session_credential')],
            },
        ),
        migrations.CreateModel(
            name='VerificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('FIRST_REDEMPTION', 'First redemption'), ('REPEAT_CHECK', 'Repeat check'), ('DECLINED', 'Declined attempt'), ('PREACTIVATION_ATTEMPT', 'Pre-activation attempt')], max_length=30)),
                ('server_time', models.DateTimeField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('previous_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsequent', to='verification.verificationevent')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='verification.consumersession')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='serialization.packageunit')),
            ],
            options={
                'db_table': 'verification_event',
            },
        ),
        migrations.CreateModel(
            name='SignedReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending signature'), ('SIGNED', 'Signed'), ('FAILED', 'Failed, will retry')], default='PENDING', max_length=20)),
                ('canonical_bytes', models.BinaryField(blank=True, null=True)),
                ('signature', models.BinaryField(blank=True, max_length=4096, null=True)),
                ('signing_key_id', models.CharField(blank=True, max_length=80)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='verification.verificationevent')),
            ],
            options={
                'db_table': 'signed_receipt',
            },
        ),
        migrations.CreateModel(
            name='VerificationOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('request_digest', models.CharField(max_length=64)),
                ('outcome', models.CharField(blank=True, choices=[('VERIFIED_FIRST', 'First verification recorded'), ('PREVIOUSLY_VERIFIED', 'Previously verified'), ('NOT_ACTIVATED', 'Not activated'), ('NOT_FOUND', 'Code not found'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled'), ('RESTRICTED', 'Restricted'), ('INVALID_CREDENTIAL', 'Invalid credential')], max_length=30)),
                ('receipt_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='verification.verificationevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='verification.consumersession')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='serialization.packageunit')),
            ],
            options={
                'db_table': 'verification_operation',
            },
        ),
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_version', models.PositiveIntegerField()),
                ('intended_action', models.CharField(default='CONFIRM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='verification.consumersession')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='serialization.packageunit')),
            ],
            options={
                'db_table': 'verification_challenge',
                'indexes': [models.Index(fields=['session', 'unit'], name='verificatio_session_c5d3b1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='verificationevent',
            index=models.Index(fields=['unit', 'server_time'], name='verificatio_unit_id_2009ac_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationevent',
            index=models.Index(fields=['session'], name='verificatio_session_c32413_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'FIRST_REDEMPTION')), fields=('unit',), name='one_first_redemption_per_unit'),
        ),
        migrations.AddIndex(
            model_name='signedreceipt',
            index=models.Index(fields=['status', 'created_at'], name='signed_rece_status_d1dcf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationoperation',
            constraint=models.UniqueConstraint(fields=('session', 'idempotency_key'), name='uniq_operation_idempotency'),
        ),
    ]
