# Generated by Django 5.2.17 on 2026-09-16 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ORGANIZATION_APPROVED', 'Organization approved'), ('ORGANIZATION_SUSPENDED', 'Organization suspended'), ('UNITS_GENERATED', 'Units generated'), ('MANUFACTURING_RECORDED', 'Manufacturing step recorded'), ('UNIT_ACTIVATED', 'Unit activated'), ('UNIT_BLOCKED', 'Unit blocked'), ('UNIT_VOIDED', 'Unit voided'), ('BATCH_RECALLED', 'Batch recalled'), ('VERIFICATION_COMMITTED', 'Verification committed'), ('KEY_REVOKED', 'Signing key revoked')], max_length=40)),
                ('actor_description', models.CharField(blank=True, max_length=200)),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_event',
                'indexes': [models.Index(fields=['organization', 'action', 'created_at'], name='audit_event_organiz_fe56ab_idx'), models.Index(fields=['unit_id'], name='audit_event_unit_id_587e35_idx'), models.Index(fields=['request_id'], name='audit_event_request_0a5a80_idx')],
            },
        ),
    ]
