# Generated by Django 5.2.17 on 2026-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('ORGANIZATION_APPROVED', 'Organization approved'), ('ORGANIZATION_SUSPENDED', 'Organization suspended'), ('UNITS_GENERATED', 'Units generated'), ('MANUFACTURING_RECORDED', 'Manufacturing step recorded'), ('UNIT_ACTIVATED', 'Unit activated'), ('UNIT_BLOCKED', 'Unit blocked'), ('UNIT_VOIDED', 'Unit voided'), ('BATCH_RECALLED', 'Batch recalled'), ('VERIFICATION_COMMITTED', 'Verification committed'), ('KEY_REVOKED', 'Signing key revoked'), ('STAFF_MFA_RESET', 'Staff second factor reset')], max_length=40),
        ),
    ]
