# Generated by Django 5.2.17 on 2026-09-16 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200)),
                ('generic', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=100)),
                ('pack_description', models.CharField(help_text="The unit as sold, e.g. 'Strip of 10 tablets'.", max_length=200)),
                ('registration_reference', models.CharField(blank=True, max_length=100)),
                ('reference_image_key', models.CharField(blank=True, help_text='Object storage key. Illustrative unless its digest is signed.', max_length=500)),
                ('reference_image_sha256', models.BinaryField(blank=True, help_text='Set only when the image is presented as authenticated (decision D7).', max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='organizations.organization')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufactured_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('planned_unit_count', models.PositiveIntegerField()),
                ('is_recalled', models.BooleanField(default=False)),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('recall_notice', models.TextField(blank=True)),
                ('recall_contact', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product')),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['manufacturer', 'brand'], name='product_manufac_875ec2_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('product', 'batch_number'), name='uniq_batch_per_product'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__gt', models.F('manufactured_on'))), name='batch_expiry_after_manufacture'),
        ),
    ]
