# Generated by Django 5.2.17 on 2026-09-16 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        ('serialization', '0001_initial'),
        ('trust', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_id', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_FAILURES', 'Completed with failures'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('requested_count', models.PositiveIntegerField(default=0)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_jobs', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_jobs', to='catalog.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_jobs', to='organizations.organization')),
            ],
            options={
                'db_table': 'activation_job',
            },
        ),
        migrations.CreateModel(
            name='ActivationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_bytes', models.BinaryField()),
                ('signature', models.BinaryField(max_length=4096)),
                ('algorithm', models.CharField(default='ML-DSA-65', max_length=20)),
                ('credential_digest', models.CharField(max_length=64)),
                ('snapshot_version', models.PositiveIntegerField()),
                ('activated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signing_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='trust.signingkey')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activation_credential', to='serialization.packageunit')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='activation.activationjob')),
            ],
            options={
                'db_table': 'activation_credential',
            },
        ),
        migrations.CreateModel(
            name='ActivationJobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('succeeded', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activation.activationjob')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_items', to='serialization.packageunit')),
            ],
            options={
                'db_table': 'activation_job_item',
            },
        ),
        migrations.AddIndex(
            model_name='activationjob',
            index=models.Index(fields=['organization', 'status'], name='activation__organiz_9422ae_idx'),
        ),
        migrations.AddIndex(
            model_name='activationcredential',
            index=models.Index(fields=['credential_digest'], name='activation__credent_207273_idx'),
        ),
        migrations.AddConstraint(
            model_name='activationjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'unit'), name='uniq_job_item_unit'),
        ),
    ]
