# Generated by Django 5.2.17 on 2026-09-16 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('serialization', '0001_initial'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=32, unique=True)),
                ('reason', models.CharField(choices=[('CODE_NOT_FOUND', 'Code not found'), ('ALREADY_VERIFIED', 'Already verified'), ('PACKAGING_SUSPICIOUS', 'Packaging looks wrong'), ('SCAN_FAILED', 'Cannot scan the code'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=64)),
                ('batch_number_text', models.CharField(blank=True, max_length=100)),
                ('pharmacy_note', models.CharField(blank=True, help_text='Free text. Requires no pharmacy account and creates no sale record.', max_length=300)),
                ('attachment_keys', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In review'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='organizations.organization')),
                ('reporter_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='verification.consumersession')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='serialization.packageunit')),
            ],
            options={
                'db_table': 'report',
                'indexes': [models.Index(fields=['status', 'reason', 'created_at'], name='report_status_0b8ab0_idx')],
            },
        ),
    ]
