# Generated by Django 5.2.17 on 2026-09-16 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serialization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingCompletionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('PRINTED', 'Printed'), ('QC_PASSED', 'QC passed'), ('QC_REJECTED', 'QC rejected'), ('COATED', 'Scratch layer applied')], max_length=20)),
                ('completed_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('source_reference', models.CharField(help_text='The operational record this assertion came from.', max_length=300)),
                ('reason', models.TextField(blank=True)),
                ('is_manufacturer_asserted', models.BooleanField(default=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_events', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_events', to='serialization.packageunit')),
            ],
            options={
                'db_table': 'manufacturing_completion_event',
                'indexes': [models.Index(fields=['unit', 'step'], name='manufacturi_unit_id_d5c4a2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('step', 'QC_REJECTED'), _negated=True), fields=('unit', 'step'), name='uniq_completion_per_unit_step')],
            },
        ),
    ]
