# Generated by Django 5.2.17 on 2026-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmembership',
            name='mfa_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmembership',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
